'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowLeft, Trash2 } from 'lucide-react';
import { calculateShares, formatRupees, type SplitMethod } from '@/lib/calculations/money';

type Share = { id: string; user_id: string; share_amount_paise: string };
type Expense = { id: string; household_id: string; title: string; amount_paise: string; expense_date: string; notes: string; expense_shares: Share[] };
type Person = { userId: string; name: string };

export function EditExpenseForm({ expense, people }: { expense: Expense; people: Person[] }) {
  const router=useRouter();
  const [title,setTitle]=useState(expense.title);const [amount,setAmount]=useState((Number(expense.amount_paise)/100).toFixed(2));const [date,setDate]=useState(expense.expense_date);const [notes,setNotes]=useState(expense.notes??'');
  const [participants,setParticipants]=useState(expense.expense_shares.map((share)=>share.user_id));const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(expense.expense_shares.map((share)=>[share.user_id,(Number(share.share_amount_paise)/100).toFixed(2)])));
  const [method,setMethod]=useState<SplitMethod>('exact');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const split=(()=>{try{return calculateShares(amount,participants.map((userId)=>({userId,value:values[userId]})),method)}catch{return null}})();
  async function save(event:React.FormEvent){event.preventDefault();if(!split){setError('Make sure the selected shares match the total amount.');return}setBusy(true);setError('');try{const shares=Object.entries(split).map(([user_id,paise])=>({user_id,share_amount:(paise/100).toFixed(2)}));const response=await fetch(`/api/backend/expenses/${expense.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.trim(),amount,expenseDate:date,notes:notes.trim(),shares})});const result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error??'Could not update the expense.');router.push(`/expenses/${expense.id}`);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:'Could not update this expense.');setBusy(false)}}
  async function remove(){if(!window.confirm(`Delete “${expense.title}”? This also removes its shares.`))return;setBusy(true);setError('');try{const response=await fetch(`/api/backend/expenses/${expense.id}`,{method:'DELETE'});const result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error??'Could not delete the expense.');router.push('/expenses');router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:'Could not delete the expense.');setBusy(false)}}
  return <><Link className="back-link" href={`/expenses/${expense.id}`}><ArrowLeft size={16}/> Expense details</Link><div className="page-heading"><span className="eyebrow">UPDATE A SHARED DETAIL</span><h1>Edit expense</h1></div><form onSubmit={save} className="form-card expense-form">{error&&<div className="form-error" role="alert">{error}</div>}<label className="field"><span>Title</span><input required maxLength={120} value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label className="field"><span>Amount</span><div className="amount-input"><span>₹</span><input required inputMode="decimal" pattern="\d+(\.\d{1,2})?" value={amount} onChange={(e)=>setAmount(e.target.value)}/></div></label><label className="field"><span>Date</span><input required type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><div className="section-label"><div><h2>Split between</h2><p>Choose who shares this expense.</p></div><span className="member-count">{participants.length} people</span></div><div className="split-method"><span>Split method</span><div className="segmented">{(['equal','exact','percentage'] as const).map((item)=><button type="button" className={method===item?'selected':''} key={item} onClick={()=>setMethod(item)}>{item==='equal'?'Equal':item==='exact'?'Exact':'Percent'}</button>)}</div></div><div className="participant-list">{people.map((person)=><label className="participant-row" key={person.userId}><input type="checkbox" checked={participants.includes(person.userId)} onChange={(e)=>setParticipants((current)=>e.target.checked?[...current,person.userId]:current.filter((id)=>id!==person.userId))}/><span className="member-avatar">{person.name.charAt(0)}</span><span className="participant-name">{person.name}</span>{participants.includes(person.userId)&&method!=='equal'&&<input className="share-input" inputMode="decimal" value={values[person.userId]??''} onChange={(e)=>setValues((current)=>({...current,[person.userId]:e.target.value}))}/>}</label>)}</div>{split&&<div className="share-preview">{people.filter((person)=>split[person.userId]!==undefined).map((person)=><div key={person.userId}><span>{person.name}</span><b>{formatRupees(split[person.userId])}</b></div>)}</div>}<label className="field"><span>Note</span><textarea rows={3} value={notes} onChange={(e)=>setNotes(e.target.value)}/></label><div className="form-actions"><button className="button button-danger" type="button" disabled={busy} onClick={remove}><Trash2 size={15}/> Delete</button><button className="button button-primary" disabled={busy||!split}>{busy?'Saving…':'Save changes'}</button></div></form></>;
}
