'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { paymentSchema } from '@/lib/validation/schemas';

type Person={userId:string;name:string};
export function PaymentForm({householdId,members,currentUserId}:{householdId:string;members:Person[];currentUserId:string}){
  const router=useRouter();const[from,setFrom]=useState(currentUserId);const[to,setTo]=useState(members.find((member)=>member.userId!==currentUserId)?.userId??'');const[amount,setAmount]=useState('');const[method,setMethod]=useState<'upi'|'cash'|'bank_transfer'|'other'>('upi');const[date,setDate]=useState(new Date().toLocaleDateString('en-CA'));const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  async function submit(event:React.FormEvent){event.preventDefault();const input={householdId,fromUser:from,toUser:to,amount,paymentMethod:method,paymentDate:date,notes};const parsed=paymentSchema.safeParse(input);if(!parsed.success){setError(parsed.error.issues[0]?.message??'Check payment details.');return}setBusy(true);setError('');try{const response=await fetch('/api/backend/payments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error??'Could not record payment.');setAmount('');setNotes('');router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:'Could not record payment.');}finally{setBusy(false)}}
  return <section className="panel-card payment-form-card"><div className="section-heading"><div className="section-icon expense-icon"><span>↗</span></div><div><h2>Record a payment</h2><p>Keep the household balance up to date.</p></div></div><form onSubmit={submit} className="payment-form">{error&&<div className="form-error" role="alert">{error}</div>}<label className="field"><span>From</span><select value={from} onChange={(event)=>setFrom(event.target.value)}>{members.map((member)=><option key={member.userId} value={member.userId}>{member.name}</option>)}</select></label><label className="field"><span>To</span><select value={to} onChange={(event)=>setTo(event.target.value)}>{members.filter((member)=>member.userId!==from).map((member)=><option key={member.userId} value={member.userId}>{member.name}</option>)}</select></label><label className="field"><span>Amount</span><div className="amount-input"><span>₹</span><input required inputMode="decimal" pattern="\d+(\.\d{1,2})?" value={amount} onChange={(event)=>setAmount(event.target.value)}/></div></label><div className="form-grid"><label className="field"><span>Method</span><select value={method} onChange={(event)=>setMethod(event.target.value as typeof method)}><option value="upi">UPI</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><label className="field"><span>Date</span><input required type="date" value={date} onChange={(event)=>setDate(event.target.value)}/></label></div><label className="field"><span>Note <em>optional</em></span><input maxLength={500} value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="For example, electricity bill"/></label><button className="button button-primary button-full" disabled={busy}>{busy?'Recording…':'Record payment'}</button></form></section>;
}
